////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Function: renderLicenseBadge - This function returns a license badge based on which license is passed in
// If there is no license, return an empty string
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
function renderLicenseBadge(license) 
{
  const apache = `[![License](https://img.shields.io/badge/License-Apache_2.0-blue.svg)](https://opensource.org/licenses/Apache-2.0)`;
  const boost = `[![License](https://img.shields.io/badge/License-Boost_1.0-lightblue.svg)](https://www.boost.org/LICENSE_1_0.txt)`;
  const mit = `[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT)`;
  const bsd = `[![License](https://img.shields.io/badge/License-BSD_3--Clause-blue.svg)](https://opensource.org/licenses/BSD-3-Clause)`;

  // Test the value passed in and return the string that contains the license badge info.
  if (license === "Apache 2.0")
  {
      return (apache);
  }
  else if (license === "Boost 1.0")
  {
      return (boost);
  }
  else if (license === "MIT")
  {
      return (mit);
  }
  else if (license === "BSD 3")
  {
      return (bsd);
  }
  // If there is no license, then return an empty string.
  else 
  {
      return ("");  
  }
}

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Function: renderLicenseSection - This function returns the license section of README.
// If there is no license, return an empty string
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
function renderLicenseSection(license) 
{
  // Create constant strings that contains the license text.
  const apache = `Apache Software License - Version 2.0 - Copyright 2021

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.`;

  const boost = `Boost Software License - Version 1.0 - August 17th, 2003

  Permission is hereby granted, free of charge, to any person or organization
  obtaining a copy of the software and accompanying documentation covered by
  this license (the "Software") to use, reproduce, display, distribute,
  execute, and transmit the Software, and to prepare derivative works of the
  Software, and to permit third-parties to whom the Software is furnished to
  do so, all subject to the following:
  
  The copyright notices in the Software and this entire statement, including
  the above license grant, this restriction and the following disclaimer,
  must be included in all copies of the Software, in whole or in part, and
  all derivative works of the Software, unless such copies or derivative
  works are solely in the form of machine-executable object code generated by
  a source language processor.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.`;

  const mit = `Copyright 2021 MIT Software License

  Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
  The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.`;

  const bsd = `Copyright 2021 BSD Software License

  Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
  
  1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
  
  2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
  
  3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
  
  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.`;

  // Test the value passed in and return the string that contains the license info.
  if (license === "Apache 2.0")
  {
      return (apache);
  }
  else if (license === "Boost 1.0")
  {
      return (boost);
  }
  else if (license === "MIT")
  {
      return (mit);
  }
  else if (license === "BSD 3")
  {
      return (bsd);
  }
  // If there is no license, then return an empty string.
  else 
  {
      return ("");  
  }
}

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Function: generateMarkdown - This function will return a string that contains the generated markdown for the 
// README file.
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
function generateMarkdown(data) 
{
  const badgeUrl = renderLicenseBadge(data.license);
  const licenseText = renderLicenseSection(data.license);
  
  let returnData = `# ${data.title}<br>${badgeUrl}<br>  
  ## Description<br>  
  ${data.description}<br>  
  ## Table of Contents<br>  
  * [Installation](#installation)<br>  
  * [Usage](#usage)<br>  
  * [License](#license)<br>  
  * [Contributing](#contributing)<br>  
  * [Tests](#tests)<br>  
  * [Questions](#questions)<br>  
  <a name="installation"></a>  
  ## Installation  
    
  ${data.install_instructions}  
  
  <a name="usage"></a>  
  
  ## Usage  
  
  ${data.usage_information}  

  <a name="license"></a>  
  
  ## License  
  
  ${licenseText}  
  
  <a name="contributing"></a>  
  
  ## Contributing  
  
  ${data.contribute_guidelines}  
  
  <a name="tests"></a>  
  
  ## Tests  
  
  ${data.test_instructions}  
  
  <a name="questions"></a>  
  
  ## Questions  
  
  GitHub Username: ${data.github_username}  
  Link to GitHub Profile: https://github.com/${data.github_username}  
  Email Address: ${data.email_address}  
  
  ${data.question_instructions}`  
  
  return (returnData);
}

// Export the generateMarkdown function of this module.
module.exports = generateMarkdown;
